apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB2cPEelkd87Wc1nTmUAODVMVMGlsVI+x8pbgDg3gk/Hk8jLghdvAB6yVtoKrZ1TMSAe6dOdfZ+o2M73+aJSZkgv+JwNB1pzrTjs9ewOu8/4sjVhnZ5EKyZP8yaEXEQ12MPr35HldohSIEqoElXJizF8Kx6B2cQL7mD8ZQ+ZfrLYHdyJqcbXPdq164HwRrcO1cTJvNve/3cI571TJ2OOd1yyh3g+9RXp0aAHsqRMsG4CrFo76DmcRkdEIjMDwCTh0TlvuOYdlNl9R1XL6Y3RXNq6NyMxiUzEK/RobjtO3RZ0+s/LEouJ8J9JNcIhBUH3VbgcuSmvNTPncz7ELfu4n6znhxdJ4A46JNm6UOUqvlhpyfhP4+f8zksJ9Bdtu8L/4F/0PvdvnsCHC3C7eCxxIq/igDFq8mQ3WDMWra5WRWvFMYPmKbrA2eGgdd9qWGTjAs8IUCyan1ENGiwsxuSeEzjpbilPWKd8jmqFolzKo64i9xHThxmHeaNqB2Zh1nQQU/ZrHAW6s5BhQAlAdYx7KN4YSc7VyWET0KHAmmch40ehK58FF13r+rA+FraAyvTU3FS+A4AULHG4PAssx9kxkOEC+2Wb5v/7b8l6P0AS4FKuw8bhihjMahVBlstjG6hhFYD5AkBpvqmEZkH2H65IDU2SU3wzDl6GmWGWAA5wwgk1UaPGvHqBrxvK/N57UqRXnmaMVESuAUcjPKwqgbS3Kv90tGKFB+EW9UNCYqcJQkeZ5kex4ulSqMF3YpAT+QFAuLxrBhc32PyWsEAl0u25R/agKJxsjyiDDXjZTdTRaFMGYiavWVXgROSh13IrsXw3yUkKuW+JCOecc8NrioUNauEzlYYYWs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

