apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCIbgia06Y/0gLR3bfrU5Q1D6b75ZzkvpRcxUVT2/eoJz+OLwSOjXaAA4NwjXLvdkyErKm8Jt7Qa1GohUFMfRIfYCiKEODPqXL05RBIjIZUMRdM52eC4pHoNDnMtmfXMDDdRLgpTktDpXvNVzVXABizfNEkE8eLDJV56qVJBA4fOUQ+d1wdFoLXOBhKGNBnFp3yYXdZHaIR0UNpmnHIFigSgn8rCP+83J2xM3np/eK3DYKMfTMdoQdTFixR41eA8+OEmdkhSnmbhCTkeBkHZj/JR1YZGs/JY1FWUVK7Ur1sD+HXhT4X7ziDM/5KO5RMs70cY5PKCKAGWSwTsFQs+uxJQGoKK1RBBQdkQsrf7J2uodc5vtsFwr1bSPgrKa3w/mEL6mDXVPmGTZpZcFZAI5qCKVtYmVtV+l9rGKDHuVyw87CWb0ebC+jR4MSaBnJgP+G3Dc8cc9GXB7aH/MMnbVD4gJ7iTKQKEY6tfekv7iQNW3477EhJJNDqWxd7cZiunqJ6ZIuA7Uw27W46q9gYGURXMg+HzKfMRtjWcdJV1GRO0hKLf2MZPGmkuLDkrEEAmLHxjtj9xuNdlXgl35DhXVZxIMkfxqYTuXLFjyNtxl2PLaaOYZtjdQuvIZ4KKfBUXARi9hnujCVkTJCHLMFQygtuO2l+upAusXgyMYdvCUlcDUWvbA6f1jE9SF854PE++9CacGIBEzlmFCPMkork34yLFlXd8myC57XsY0sb/Vdd4gPyoVrq1yoldO3Pmh35ZXt1FcIAlwQi0JOgCxGxKGTb4fWKRgrq0K991Jd8KqdnwgYNyEKaQGu5PvS3zXPCfM35703ZfeSXTof3bm15o27XZ7UTuII=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

