apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCGz9h+TusiceyHSY87ln55I2KwXu4gd2SNdZTgaXPVb0rLuqE3wz0RuEl83VJO1SPo1uMftCXe33wcqlTRxxeIArRLvSBFgThduarW3tw3bOb0dnLf36rIWdWNKVD3JDI6ifwt+xOnVFTSDhP+2O28pTrt0ojKuQoCRPIB5As5kXEYqD8E6E0pO2tZOrRxH1IItmUhJskenY4N6Y9XmZykCwzY/w8DanAQ1Zb3Y25jJRxld7aHsqNK/2ftH2H/0sf/3DiVcWuFDiiOCOvISkTxm+9UUmwnzhxRDyRo2d0FZoeulTnK3PYv/gK73oI2Fm28xWfEDlkS4+asCV/TZOxNlaVqGNEjCuO1o+XlrUKhh5epwTbfnzEmXhnV1wrSjPfE9deRxtHHGsf4a1ye3XnRm8kbk+/raIg0juX1f9yxrzbePvmm6vo8+PlXGzTKSWklHYxSlj8WEHc74JyHSf96v+chgTe3gXzb4VPJ8AKUzAYMyccfjsE5qQMzMKzvgx1xDAVdq2UfMTJkjclaehQH9ybrkU9NhqvSKGPz08DsdvS+r27aDkCkiZ2vfjSTQcHFZERxg5BkcHlAVIgLtCYC/L/bwhq7orrAI1oxexroGqEmuAPTUg1yLXsKiJqIyNMjYI3kxXY6xgcNdWg3mZfRKMRwAbMY5QIKO+eLVywo2tbbsN2sbrkHBzlOj075/e0OAsPkvOkbRYhqVtkBHWePgkgEba1ZZ2CEDG4T6EcoZy5rQhfKinmtGsZaXdORoL4n/f31ZRbVvwPpbXUMewKET89uNw46c0VzPJrYMgsOU84YaTS0mNLJi/cy1a6grfXyOQnRFZlgjX3sgmecCwnz2HNwJ1Y=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

