apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAOGuoXwY7hOL0X3vR2K/TN6/RE63JtdSHwH/wQYHHR8k8ViJwG2O/TQVCRU6BtUYUGAyFFvgN4+eptU39h9UrNjDzHlebrFlw5AIK76TS4DbdFEYg5cs6DpQXBCcFHY+WicgMqpN8hRcN5g3s40Gs4+bzKhoIq5nIDclmvoJ2JYjJjtm4UK9HRRfv3IpmHdQEyT6ZWRiefjpbm4uTHP1dkarl2qjMItH1XKKr5nLWsYok+49kaI/sqACcJQvJN7V9q33IlTTdSBwi2rC36AK9iw4bRJmdrp22KNHUs+NViXEHWJHS8UHtB9CF2AsR1zagpyIVShZV7g8LgOh1pHB6D0yCiy/4/yssiMgJdiiteCGlAYY0l6IFVS20mbhlwRJoaxX+50C/XLwyV/oobuFl502eWuW078MN0/4qlk8MBMLLgESvZDhRHvJCzV2ERmLeKMj9tc1l6JCP/vWPyTMwrz7w+G6gBme2plHTLUKlFtU0luj485YwDUtK7zbaK23BYV6JFLRsStnTIITplXaqI9UkGPtPmQiqH2zmwxj3zPLJHY1Xs6SV9/KesE4PIBVbKjiASF8CKdCEhVZWfM0SQuIzti9MSybip35oNJs/i61vyJMWoZIYF66SkzzwzRcrzAO2RkOVeHU2DJkPUB6VFlCUcVLFPc5CMl3Nt6RB22aQqtCGc0RhgHuOBE5MZM0sMIN6MmNVDocV+VXBkInt1g4bWA748Er8Wfw7gofRBPfv3SYdufRwGtwS9srv/9beQSji3neh7deiAqyT/AyripGM/2ftGvCh0BWs7FDefVvBZRbjCGQcqh42B5u5s5WirSyfTi5VspWtu5S20IZg8nkqHIbs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

