apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA+omihYcdenf/f6rbt92XQJFYdPH5OmGk7n461vTGWo735cSBHZJIXgv7jaG1kK8mG3d0cwmQ+ZTANDSIBBpDeTx+eml3l+xRjUnwe/olzWuY0885HSofam331FUuulVfPHxf6KZF9wmQ1SBPdhOGeCC1XZktF9a6c/DNzZR56sVE8GL9FO5YZwPIComYoyKKz9iXuA/R3PV+U0M37EJDajXLfNHYFB/lN+kjCxecf6PAs+9MVlI0TQalHjL69qv/vODYnSVNk33SKJihswWDtLhBQk3NlRfKoLEEfUb4b26W5nwbEI73vLs1/dcvIVUig2iAjd5F0tx9dVKzFgHei3gXkxT+/nBEmQ+N2emdDtTFe586HNfnRNkyOvASoZaUt12zp9FbiDHJlY0QNx+dRSocnOmOi4qjBp5dvCVcNQTGsJWUWgYr5SDA7WRCQAvvI6SPv8Y8tGg3SRwlAhvcVBEuGV7UvdrXR0e8mK8qrxQJC7OebQPcuTfV58Uj46cuxKG1ag4rjTDxukOFmi1Ggz+6HrV3K76AbrSg4zBM+HKngBUfOQ6BhdxrWuSi73wHeCZudb/zLGeaFLAmtX7gOJy/11fOO7Gfma03loGgkSkFZH9nzk0zUjJ5VK/9q+9/fkysBYNjQWyP5t3NnS5IRmLRUD//oMkfV+SdKhTVW41z0+fmFGmNlmK+G72qrRp0kUNvDR7DSa4OX78voIWxNHo1wIQhn9w6aNXQTFwdIvtURGiBh1csSZnF6empnC9j1nxYl7CB6tqTuPYL4/bMD2TkOUJfDhUEPSfckyuhA9mEG25qxO4U/+BOrQ9TrFp/NbemdnPFm4m1t0xLfq+UxjhKqtIk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

