apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA49gvBW1stgqmGI6oo4xaW7PM3IF9BffaaddLVXbUCl7v9nALq//WNJRrIT/ZqC0bEvsoho5IOPQ1geUEO+EqHlDMn0xT8u7sQ0dxNQj2DFLgSJHIY2LJvijxMZGLoJ7JKokq86EMY5oX2WQ/8NvWNxb0D8ym7UU+MhF1p1eTc5bNyAJ77ZMDDHs1b/ErcQcC9NDJw1PT10t+gZ18UB04/F+q/mEMQ8503d2w7lHP6CyUxcnxQ4izcvZ53baDqMhYmF8Z2QO99EAmEqR9lINQ/8GdCOkzIsxmtuHfpkundC3pO8Gz0bf9FKoDpi6ykgE+4uSDDI2voUe3HJ/P5u/ln9z3r+012Pi6vj7EsdwoeBja23SF1JO3/OytatEEMxOPee+RSnnn8LcUF/Ur+IB06kmDQY1oLFZ4Z2YyifXlOL170JkOCuEPKm4lHWtcWXU92SSJJJEO2/K+nFBG7gEKml/45gwhzpL6Cu1ZA/Of6OdoEhloubghkuidplQUxIx/8Ke3FSfK1+Z7j62ytk/y5rut9PT3cNyWPzjy+mseu5CFxIMs8Sml79ZASPoYQn1yr52nv2SV8ijrnSxEL4/V5RZYGDO7uRNcAIJ6acKPPDx6i0P0yelPjWVpDHiLRPybqxufxnB+zH067r9gTO+MvTdv/c1EcgG8CxMbOk1dcfkc3zSTXz0vHc/QEiU2QTYtU8cT6P37PJDnxaybWKjCYGSsyAx6fHEIVMIOF50cM0tM51UAEuGVy+rB1ojdHKb83gQW3WpvbGJVeZfEZZaCXkCFNUdEoxYNIxXm4mcoS/9aUK5qSr7gDFLIW6ArFZBEIaYLODZyrs3nw5hxtVYKIxOhocTk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

