apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgALCl0JjeV3rMevRWsh5noRCdrgGSPTzQDYmD1srpplV3z5h83LtMi6NoTdlDpF4SB6PbFMKBbN80g390Tan8M7BFNavpRaBdC8SZMYanhdh4g8jB0wyQSiF35mxhd0Y4jk780e95TvJf+XgbF0kJiwkbrwkN77D0OidY8QBHeoEyzIArwxXF4qS7ShRG/WqagdEtmvKH3yoVwTufNxd7fMCwRvQ7fUDuM252OlY3moOllwySlZ9NT2SnkS/n1JpAnPbEJqoWRTnYOsECORFiHmBjzFmac5G9UWFNBx+OFzimy7XLqrxfb0q9KdLobr29VOjU/jYIIRbOhXYQ56As7j37p7BS5WynyN/UpfFte3vTkydsBuQKShMcUVr3mPIGByA3ejYREcIe+clTX6dZgadUBatwwvqviCY4oQXbWDy0RU3UftWDiTtyIPZCb7PIhSrDxY+sSZCwjjzlFM8adQ3TqyAFlTnPcssQq2NX3TmBoR1fPUwZYbr4ZGkXT/Rs8QQuVaxqHetEh3Ibcnl8jtQNmZPekMD4ScIudyVrXlfzZQoUWUW9CcUDwijuu00qNRb6KMydPc0iQFJPZkMU9Inn7KJhw8HYu5b/fbJbuF37WfQnNreC4hGih3n/3a70BJf2VAke37yPcwG9zVznIiSxNfv8z7rwUHiUQEhOZqAK+L2XRk0L7Y2YNkTb8fHcDFigxjpvJybvUBsUJHq6KFZn6FUiGq8MwBVFreNKEQFSDAgd699DdMflUHwyGRstECHl+CxLLLt9ZGGcVmFv8+9aPIHjUgCa5IUSN1njof9Pn39WHqOy2aBrBSGlZMe5T4W05/pPhaH7WURlLVNW2b/+oRRys=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

